/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs2263_project;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
        StartUI mainMenu = new StartUI();

        Application.launch(mainMenu.getClass());
    }
}
